 apiVersion: v1
 kind: ConfigMap
 metadata:
  name: foodiehub-config
  namespace: foodiehub
 data:
  DB_HOST: "postgres-service"
  DB_NAME: "foodiehub"
  DB_USER: "postgres"
  SPRING_PROFILES_ACTIVE: "docker"