apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodiehub-backend
  namespace: foodiehub
  labels:
    app: foodiehub-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foodiehub-backend
  template:
    metadata:
      labels:
        app: foodiehub-backend
    spec:
      containers:
      - name: foodiehub-backend
        image: foodiehub-backend:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_NAME
          value: "foodiehub"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
